/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export type ExternalBlob = Uint8Array;
export interface InspectionItem {
  'id' : ItemId,
  'status' : ItemStatus,
  'name' : string,
  'note' : string,
  'part' : [] | [PartInfo],
  'category' : string,
}
export type ItemId = bigint;
export interface ItemInput {
  'status' : ItemStatus,
  'name' : string,
  'note' : string,
  'part' : [] | [PartInfo],
  'category' : string,
}
export type ItemStatus = { 'ok' : null } |
  { 'replace' : null } |
  { 'attention' : null };
export type PartAvailability = { 'order' : null } |
  { 'available' : null } |
  { 'unavailable' : null };
export interface PartInfo {
  'name' : string,
  'availability' : PartAvailability,
  'price' : bigint,
}
export interface Photo {
  'id' : PhotoId,
  'blob' : ExternalBlob,
  'mimeType' : string,
  'filename' : string,
}
export type PhotoId = bigint;
export interface PhotoInput {
  'blob' : ExternalBlob,
  'mimeType' : string,
  'filename' : string,
}
export type ReportFilter = { 'all' : null } |
  { 'hasReplace' : null } |
  { 'hasAttention' : null };
export type ReportId = bigint;
export interface ReportInput {
  'vehicleName' : string,
  'inspectionDate' : string,
  'year' : bigint,
  'plateNumber' : string,
}
export interface ReportListItem {
  'id' : ReportId,
  'vehicleName' : string,
  'inspectionDate' : string,
  'createdAt' : Timestamp,
  'year' : bigint,
  'summary' : ReportSummary,
  'updatedAt' : Timestamp,
  'plateNumber' : string,
}
export type ReportSort = { 'newestFirst' : null } |
  { 'oldestFirst' : null };
export interface ReportSummary {
  'replaceCount' : bigint,
  'attentionCount' : bigint,
  'okCount' : bigint,
  'totalItems' : bigint,
  'estimatedPartCost' : bigint,
}
export interface ReportView {
  'id' : ReportId,
  'vehicleName' : string,
  'inspectionDate' : string,
  'createdAt' : Timestamp,
  'year' : bigint,
  'summary' : ReportSummary,
  'updatedAt' : Timestamp,
  'plateNumber' : string,
  'items' : Array<InspectionItem>,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Add an inspection item to a report. Returns the new item id.
   */
  'addItem' : ActorMethod<[ReportId, ItemInput], [] | [ItemId]>,
  /**
   * / Attach a photo to an inspection item. Returns the new photo id.
   */
  'addPhoto' : ActorMethod<[ReportId, ItemId, PhotoInput], [] | [PhotoId]>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create a new report and return its id.
   */
  'createReport' : ActorMethod<[ReportInput], ReportId>,
  /**
   * / Remove an inspection item from a report. Returns false when not found.
   */
  'deleteItem' : ActorMethod<[ReportId, ItemId], boolean>,
  /**
   * / Remove a photo from an inspection item. Returns false when not found.
   */
  'deletePhoto' : ActorMethod<[ReportId, ItemId, PhotoId], boolean>,
  /**
   * / Delete a report and all of its items and photos.
   */
  'deleteReport' : ActorMethod<[ReportId], boolean>,
  'execute' : ActorMethod<[string], Result>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Fetch a single report with its items and derived summary.
   */
  'getReport' : ActorMethod<[ReportId], [] | [ReportView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List the photos attached to an inspection item.
   */
  'listPhotos' : ActorMethod<[ReportId, ItemId], Array<Photo>>,
  /**
   * / List reports, newest first, optionally filtered by search term and status.
   */
  'listReports' : ActorMethod<
    [string, ReportFilter, ReportSort],
    Array<ReportListItem>
  >,
  'schema' : ActorMethod<[], string>,
  /**
   * / Replace an inspection item's fields. Returns false when not found.
   */
  'updateItem' : ActorMethod<[ReportId, ItemId, ItemInput], boolean>,
  /**
   * / Update a report header. Returns false when the report does not exist.
   */
  'updateReport' : ActorMethod<[ReportId, ReportInput], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];