/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const ReportId = IDL.Nat;
export const ItemStatus = IDL.Variant({
  'ok' : IDL.Null,
  'replace' : IDL.Null,
  'attention' : IDL.Null,
});
export const PartAvailability = IDL.Variant({
  'order' : IDL.Null,
  'available' : IDL.Null,
  'unavailable' : IDL.Null,
});
export const PartInfo = IDL.Record({
  'name' : IDL.Text,
  'availability' : PartAvailability,
  'price' : IDL.Nat,
});
export const ItemInput = IDL.Record({
  'status' : ItemStatus,
  'name' : IDL.Text,
  'note' : IDL.Text,
  'part' : IDL.Opt(PartInfo),
  'category' : IDL.Text,
});
export const ItemId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PhotoInput = IDL.Record({
  'blob' : ExternalBlob,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
});
export const PhotoId = IDL.Nat;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ReportInput = IDL.Record({
  'vehicleName' : IDL.Text,
  'inspectionDate' : IDL.Text,
  'year' : IDL.Nat,
  'plateNumber' : IDL.Text,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const Timestamp = IDL.Int;
export const ReportSummary = IDL.Record({
  'replaceCount' : IDL.Nat,
  'attentionCount' : IDL.Nat,
  'okCount' : IDL.Nat,
  'totalItems' : IDL.Nat,
  'estimatedPartCost' : IDL.Nat,
});
export const InspectionItem = IDL.Record({
  'id' : ItemId,
  'status' : ItemStatus,
  'name' : IDL.Text,
  'note' : IDL.Text,
  'part' : IDL.Opt(PartInfo),
  'category' : IDL.Text,
});
export const ReportView = IDL.Record({
  'id' : ReportId,
  'vehicleName' : IDL.Text,
  'inspectionDate' : IDL.Text,
  'createdAt' : Timestamp,
  'year' : IDL.Nat,
  'summary' : ReportSummary,
  'updatedAt' : Timestamp,
  'plateNumber' : IDL.Text,
  'items' : IDL.Vec(InspectionItem),
});
export const Photo = IDL.Record({
  'id' : PhotoId,
  'blob' : ExternalBlob,
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
});
export const ReportFilter = IDL.Variant({
  'all' : IDL.Null,
  'hasReplace' : IDL.Null,
  'hasAttention' : IDL.Null,
});
export const ReportSort = IDL.Variant({
  'newestFirst' : IDL.Null,
  'oldestFirst' : IDL.Null,
});
export const ReportListItem = IDL.Record({
  'id' : ReportId,
  'vehicleName' : IDL.Text,
  'inspectionDate' : IDL.Text,
  'createdAt' : Timestamp,
  'year' : IDL.Nat,
  'summary' : ReportSummary,
  'updatedAt' : Timestamp,
  'plateNumber' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addItem' : IDL.Func([ReportId, ItemInput], [IDL.Opt(ItemId)], []),
  'addPhoto' : IDL.Func([ReportId, ItemId, PhotoInput], [IDL.Opt(PhotoId)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createReport' : IDL.Func([ReportInput], [ReportId], []),
  'deleteItem' : IDL.Func([ReportId, ItemId], [IDL.Bool], []),
  'deletePhoto' : IDL.Func([ReportId, ItemId, PhotoId], [IDL.Bool], []),
  'deleteReport' : IDL.Func([ReportId], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getReport' : IDL.Func([ReportId], [IDL.Opt(ReportView)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listPhotos' : IDL.Func([ReportId, ItemId], [IDL.Vec(Photo)], ['query']),
  'listReports' : IDL.Func(
      [IDL.Text, ReportFilter, ReportSort],
      [IDL.Vec(ReportListItem)],
      ['query'],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'updateItem' : IDL.Func([ReportId, ItemId, ItemInput], [IDL.Bool], []),
  'updateReport' : IDL.Func([ReportId, ReportInput], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const ReportId = IDL.Nat;
  const ItemStatus = IDL.Variant({
    'ok' : IDL.Null,
    'replace' : IDL.Null,
    'attention' : IDL.Null,
  });
  const PartAvailability = IDL.Variant({
    'order' : IDL.Null,
    'available' : IDL.Null,
    'unavailable' : IDL.Null,
  });
  const PartInfo = IDL.Record({
    'name' : IDL.Text,
    'availability' : PartAvailability,
    'price' : IDL.Nat,
  });
  const ItemInput = IDL.Record({
    'status' : ItemStatus,
    'name' : IDL.Text,
    'note' : IDL.Text,
    'part' : IDL.Opt(PartInfo),
    'category' : IDL.Text,
  });
  const ItemId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PhotoInput = IDL.Record({
    'blob' : ExternalBlob,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
  });
  const PhotoId = IDL.Nat;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ReportInput = IDL.Record({
    'vehicleName' : IDL.Text,
    'inspectionDate' : IDL.Text,
    'year' : IDL.Nat,
    'plateNumber' : IDL.Text,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const Timestamp = IDL.Int;
  const ReportSummary = IDL.Record({
    'replaceCount' : IDL.Nat,
    'attentionCount' : IDL.Nat,
    'okCount' : IDL.Nat,
    'totalItems' : IDL.Nat,
    'estimatedPartCost' : IDL.Nat,
  });
  const InspectionItem = IDL.Record({
    'id' : ItemId,
    'status' : ItemStatus,
    'name' : IDL.Text,
    'note' : IDL.Text,
    'part' : IDL.Opt(PartInfo),
    'category' : IDL.Text,
  });
  const ReportView = IDL.Record({
    'id' : ReportId,
    'vehicleName' : IDL.Text,
    'inspectionDate' : IDL.Text,
    'createdAt' : Timestamp,
    'year' : IDL.Nat,
    'summary' : ReportSummary,
    'updatedAt' : Timestamp,
    'plateNumber' : IDL.Text,
    'items' : IDL.Vec(InspectionItem),
  });
  const Photo = IDL.Record({
    'id' : PhotoId,
    'blob' : ExternalBlob,
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
  });
  const ReportFilter = IDL.Variant({
    'all' : IDL.Null,
    'hasReplace' : IDL.Null,
    'hasAttention' : IDL.Null,
  });
  const ReportSort = IDL.Variant({
    'newestFirst' : IDL.Null,
    'oldestFirst' : IDL.Null,
  });
  const ReportListItem = IDL.Record({
    'id' : ReportId,
    'vehicleName' : IDL.Text,
    'inspectionDate' : IDL.Text,
    'createdAt' : Timestamp,
    'year' : IDL.Nat,
    'summary' : ReportSummary,
    'updatedAt' : Timestamp,
    'plateNumber' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addItem' : IDL.Func([ReportId, ItemInput], [IDL.Opt(ItemId)], []),
    'addPhoto' : IDL.Func(
        [ReportId, ItemId, PhotoInput],
        [IDL.Opt(PhotoId)],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createReport' : IDL.Func([ReportInput], [ReportId], []),
    'deleteItem' : IDL.Func([ReportId, ItemId], [IDL.Bool], []),
    'deletePhoto' : IDL.Func([ReportId, ItemId, PhotoId], [IDL.Bool], []),
    'deleteReport' : IDL.Func([ReportId], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getReport' : IDL.Func([ReportId], [IDL.Opt(ReportView)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listPhotos' : IDL.Func([ReportId, ItemId], [IDL.Vec(Photo)], ['query']),
    'listReports' : IDL.Func(
        [IDL.Text, ReportFilter, ReportSort],
        [IDL.Vec(ReportListItem)],
        ['query'],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'updateItem' : IDL.Func([ReportId, ItemId, ItemInput], [IDL.Bool], []),
    'updateReport' : IDL.Func([ReportId, ReportInput], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };